export const SIGNIN_REQUEST = 'SIGNIN_REQUEST';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAILURE = 'SIGNIN_FAILURE';

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_SEND_CONFIRMATION = 'SIGNUP_SEND_CONFIRMATION';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const CONFIRMATION_REQUEST = 'CONFIRMATION_REQUEST';
export const CONFIRMATION_SUCCESS = 'CONFIRMATION_SUCCESS';
export const CONFIRMATION_FAILURE = 'CONFIRMATION_FAILURE';



